<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/7/22
 * Time: 14:50
 */

namespace app\index\controller;

use think\Controller;
use think\Db;

class Base extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $cateres = Db::name('cate')->order('id desc')->select();
        $this->assign('cates',$cateres);
    }
}